# Numpy Basics

In [6]:
import numpy as np
my_arr = np.array([[2,4,6]],np.int64)
my_arr[0]

array([2, 4, 6])

In [2]:
my_arr[0,0]

np.int64(2)

In [7]:
my_arr.shape

(1, 3)

In [8]:
my_arr.dtype

dtype('int64')

In [10]:
my_arr[0,2]=69
my_arr

array([[ 2,  4, 69]])

# Intrinsic numpy array creation objects


In [11]:
## Basically this are the given funtions to create arrays in numpy


In [13]:
zeros= np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
Auto_array = np.arange(15)
Auto_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
Lspace= np.linspace(1,4,8)
Lspace

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [19]:
emp = np.empty((3,4))
emp

array([[1.15936777e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.29060531e-306, 8.75983079e+164, 6.50095884e-091,
        3.31333426e-033],
       [3.57232198e-062, 7.31505923e-042, 3.99910963e+252,
        3.89187487e-033]])

In [22]:
i= np.identity(10)
i

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [40]:
x= [[1,44,3],[4,5,6],[7,8,9]]
ar3= np.array(x)
ar3

array([[ 1, 44,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [41]:
ar3.sum(axis=0)

array([12, 57, 18])

In [42]:
ar3.sum(axis=1)

array([48, 15, 24])

In [43]:
ar3.T

array([[ 1,  4,  7],
       [44,  5,  8],
       [ 3,  6,  9]])

In [44]:
ar3.flat

In [45]:
for item in ar3.flat:
    print(item)

1
44
3
4
5
6
7
8
9


In [46]:
ar3.nbytes

72

In [4]:
m1 = [[1,2,3],[4,5,6],[7,1,0]]
ar1= np.array(m1)
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [5]:
m2 = [[22,33,44],[12,34,56],[56,87,91]]
ar2= np.array(m2)
ar2

array([[22, 33, 44],
       [12, 34, 56],
       [56, 87, 91]])

In [6]:
ar1+ar2

array([[23, 35, 47],
       [16, 39, 62],
       [63, 88, 91]])

In [7]:
ar1*ar2

array([[ 22,  66, 132],
       [ 48, 170, 336],
       [392,  87,   0]])

In [8]:
np.sqrt(ar2)

array([[4.69041576, 5.74456265, 6.63324958],
       [3.46410162, 5.83095189, 7.48331477],
       [7.48331477, 9.32737905, 9.53939201]])

In [11]:
ar1.max()

np.int64(7)

In [12]:
ar2.min()

np.int64(12)

# why Numpy?

** It takes less bites + also efficient for data analysis**